// Export pages
export '/pages/client/services/services_widget.dart' show ServicesWidget;
export '/pages/client/profile/notification/notification_widget.dart'
    show NotificationWidget;
export '/pages/client/rides/pending_request/pending_request_widget.dart'
    show PendingRequestWidget;
export '/pages/client/rides/comfirmation/comfirmation_widget.dart'
    show ComfirmationWidget;
export '/pages/client/rides/tracking/tracking_widget.dart' show TrackingWidget;
export '/pages/client/a_i_assistant/a_i_assistant_widget.dart'
    show AIAssistantWidget;
export '/pages/client/others/privacy_policy/privacy_policy_widget.dart'
    show PrivacyPolicyWidget;
export '/pages/client/others/terms_and_conditions/terms_and_conditions_widget.dart'
    show TermsAndConditionsWidget;
export '/pages/client/auth/sign_in/sign_in_widget.dart' show SignInWidget;
export '/pages/client/auth/sign_up/sign_up_widget.dart' show SignUpWidget;
export '/pages/client/home/home_widget.dart' show HomeWidget;
export '/pages/driver/profile/driver_profile/driver_profile_widget.dart'
    show DriverProfileWidget;
export '/pages/driver/profile/driver_information/driver_information_widget.dart'
    show DriverInformationWidget;
export '/pages/driver/others/driverprivacypolicy/driverprivacypolicy_widget.dart'
    show DriverprivacypolicyWidget;
export '/pages/driver/others/driver_terms/driver_terms_widget.dart'
    show DriverTermsWidget;
export '/pages/driver/rides/incoming_request/incoming_request_widget.dart'
    show IncomingRequestWidget;
export '/pages/driver/rides/active_ride/active_ride_widget.dart'
    show ActiveRideWidget;
export '/pages/client/others/quotes/quotes_widget.dart' show QuotesWidget;
export '/pages/driver/others/driver_error_page/driver_error_page_widget.dart'
    show DriverErrorPageWidget;
export '/pages/client/others/error_page/error_page_widget.dart'
    show ErrorPageWidget;
export '/pages/client/courier/courier_booking/courier_booking_widget.dart'
    show CourierBookingWidget;
export '/pages/client/tours/school_trip_booking/school_trip_booking_widget.dart'
    show SchoolTripBookingWidget;
export '/pages/client/tours/individual_tours/individual_tours_widget.dart'
    show IndividualToursWidget;
export '/pages/client/hire/car_hire/car_hire_widget.dart' show CarHireWidget;
export '/pages/admin/rides/liveridetracker/liveridetracker_widget.dart'
    show LiveridetrackerWidget;
export '/pages/admin/admin_setting/admin_setting_widget.dart'
    show AdminSettingWidget;
export '/pages/admin/admin_profile/admin_profile_widget.dart'
    show AdminProfileWidget;
export '/pages/admin/notifications/admin_notifications/admin_notifications_widget.dart'
    show AdminNotificationsWidget;
export '/pages/admin/auth/admin_login/admin_login_widget.dart'
    show AdminLoginWidget;
export '/pages/admin/reports/admin_reports/admin_reports_widget.dart'
    show AdminReportsWidget;
export '/pages/admin/reports/report_details/report_details_widget.dart'
    show ReportDetailsWidget;
export '/pages/client/profile/my_profile/my_profile_widget.dart'
    show MyProfileWidget;
export '/pages/admin/drivers/admin_drivers/admin_drivers_widget.dart'
    show AdminDriversWidget;
export '/pages/driver/profile/update_driver_profile/update_driver_profile_widget.dart'
    show UpdateDriverProfileWidget;
export '/pages/driver/rides/accepted_ride/accepted_ride_widget.dart'
    show AcceptedRideWidget;
export '/pages/client/rides/booking/booking_widget.dart' show BookingWidget;
export '/pages/client/flights/flight_booking/flight_booking_widget.dart'
    show FlightBookingWidget;
export '/pages/admin/flights/admin_flights/admin_flights_widget.dart'
    show AdminFlightsWidget;
export '/pages/client/others/settings/settings_widget.dart' show SettingsWidget;
export '/pages/client/others/privacy_security/privacy_security_widget.dart'
    show PrivacySecurityWidget;
export '/pages/client/profile/language_preferences/language_preferences_widget.dart'
    show LanguagePreferencesWidget;
export '/pages/client/others/storage_and_data/storage_and_data_widget.dart'
    show StorageAndDataWidget;
export '/pages/client/others/help_center/help_center_widget.dart'
    show HelpCenterWidget;
export '/pages/client/others/contact_support/contact_support_widget.dart'
    show ContactSupportWidget;
export '/pages/client/others/f_a_qs/f_a_qs_widget.dart' show FAQsWidget;
export '/pages/client/rides/rate_driver/rate_driver_widget.dart'
    show RateDriverWidget;
export '/pages/client/others/terms_of_service/terms_of_service_widget.dart'
    show TermsOfServiceWidget;
export '/pages/client/others/policies/policies_widget.dart' show PoliciesWidget;
export '/pages/client/profile/change_password/change_password_widget.dart'
    show ChangePasswordWidget;
export '/pages/driver/auth/driver_login/driver_login_widget.dart'
    show DriverLoginWidget;
export '/pages/admin/drivers/update_driver/update_driver_widget.dart'
    show UpdateDriverWidget;
export '/pages/admin/drivers/add_driver/add_driver_widget.dart'
    show AddDriverWidget;
export '/pages/driver/notifications/driver_notifications/driver_notifications_widget.dart'
    show DriverNotificationsWidget;
export '/pages/driver/others/driver_settings/driver_settings_widget.dart'
    show DriverSettingsWidget;
export '/pages/admin/flights/flight_bookings_admin/flight_bookings_admin_widget.dart'
    show FlightBookingsAdminWidget;
export '/pages/admin/flights/add_flight_admin/add_flight_admin_widget.dart'
    show AddFlightAdminWidget;
export '/pages/admin/courier/admin_couriers/admin_couriers_widget.dart'
    show AdminCouriersWidget;
export '/pages/admin/hotels/hotel_bookings_admin/hotel_bookings_admin_widget.dart'
    show HotelBookingsAdminWidget;
export '/pages/admin/tours/tour_booking_admin/tour_booking_admin_widget.dart'
    show TourBookingAdminWidget;
export '/pages/admin/hotels/add_hotel/add_hotel_widget.dart'
    show AddHotelWidget;
export '/pages/admin/tours/add_tour/add_tour_widget.dart' show AddTourWidget;
export '/pages/admin/hire/add_vehicle/add_vehicle_widget.dart'
    show AddVehicleWidget;
export '/pages/client/hire/find_your_car/find_your_car_widget.dart'
    show FindYourCarWidget;
export '/pages/client/flights/available_flights/available_flights_widget.dart'
    show AvailableFlightsWidget;
export '/pages/client/hotels/availablehotelpage/availablehotelpage_widget.dart'
    show AvailablehotelpageWidget;
export '/pages/client/tours/available_tour_places/available_tour_places_widget.dart'
    show AvailableTourPlacesWidget;
export '/pages/admin/notifications/admin_requests/admin_requests_widget.dart'
    show AdminRequestsWidget;
export '/pages/admin/flights/update_flight/update_flight_widget.dart'
    show UpdateFlightWidget;
export '/pages/admin/tours/admin_tours/admin_tours_widget.dart'
    show AdminToursWidget;
export '/pages/admin/hire/admin_vehicles/admin_vehicles_widget.dart'
    show AdminVehiclesWidget;
export '/pages/admin/hire/update_vehicle/update_vehicle_widget.dart'
    show UpdateVehicleWidget;
export '/pages/admin/hotels/update_hotel/update_hotel_widget.dart'
    show UpdateHotelWidget;
export '/pages/admin/hotels/admin_hotels/admin_hotels_widget.dart'
    show AdminHotelsWidget;
export '/pages/admin/tours/update_tour_admin/update_tour_admin_widget.dart'
    show UpdateTourAdminWidget;
export '/pages/admin/rides/admin_rides/admin_rides_widget.dart'
    show AdminRidesWidget;
export '/pages/client/hotels/book_hotel_page/book_hotel_page_widget.dart'
    show BookHotelPageWidget;
export '/pages/admin/admin_dashboard/admin_dashboard_widget.dart'
    show AdminDashboardWidget;
export '/pages/driver/rides/ride_history/ride_history_widget.dart'
    show RideHistoryWidget;
export '/pages/client/courier/courier_pricing/courier_pricing_widget.dart'
    show CourierPricingWidget;
export '/pages/admin/drivers/admin_edit_driver/admin_edit_driver_widget.dart'
    show AdminEditDriverWidget;
export '/pages/client/courier/courier_tracking/courier_tracking_widget.dart'
    show CourierTrackingWidget;
export '/pages/others/about_us/about_us_widget.dart' show AboutUsWidget;
export '/pages/driver/driver_dashboard/driver_dashboard_widget.dart'
    show DriverDashboardWidget;
